[package]
name = "evaluation-juillet-2024"
version = "0.1.0"
edition = "2021"
exclude = ["/app", "/node_modules"]
default-run = "evaluation-juillet-2024"
resolver = "2"

[dependencies]
diesel.workspace = true
dotenvy = "0.15"
uuid = "1"
jwt = "0.16"
serde = { version = "1", features = ["derive"] }
anyhow = "1"
thiserror = "1"
hmac = "0.12"
sha2 = "0.10"
time = { version = "0.3", features = [
    "serde",
    "macros",
    "serde-human-readable",
] }
bigdecimal = { version = "0.4", features = ["serde"] }
regex = "1.10"
rand = "0.8"
tokio = { workspace = true, features = ["sync", "macros", "rt-multi-thread"] }
csv = "1"
convert_case = "0.6"
tonic.workspace = true
prost.workspace = true

[build-dependencies]
tonic-build = { version = "0.11" }

[workspace.dependencies]
tonic = { version = "0.11" }
prost = { version = "0.12" }
diesel = { version = "2", features = [
    "postgres",
    "r2d2",
    "uuid",
    "time",
    "numeric",
] }
tokio = { version = "1" }
